package stdlib

// ArcaValidatable is implemented by constrained types that have validation rules.
// Auto-generated by the Arca transpiler for types with constraints.
type ArcaValidatable interface {
	ArcaValidate() error
}

// ArcaValidateIfPossible calls ArcaValidate() if the value implements ArcaValidatable.
func ArcaValidateIfPossible(v any) error {
	if val, ok := v.(ArcaValidatable); ok {
		return val.ArcaValidate()
	}
	return nil
}
